language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rspec spec
  - bundle exec cucumber features
