require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SprintsController do

  def mock_sprint(stubs={})
    @mock_sprint ||= mock_model(Sprint, stubs).as_null_object
  end
  
  # todo: nest under project?

  # describe "GET index" do
  #   it "assigns all sprints as @sprints" do
  #     Sprint.stub(:all) { [mock_sprint] }
  #     get :index
  #     assigns(:sprints).should eq([mock_sprint])
  #   end
  # end
  # 
  # describe "GET show" do
  #   it "assigns the requested sprint as @sprint" do
  #     Sprint.stub(:find).with("37") { mock_sprint }
  #     get :show, :id => "37"
  #     assigns(:sprint).should be(mock_sprint)
  #   end
  # end
  # 
  # describe "GET new" do
  #   it "assigns a new sprint as @sprint" do
  #     Sprint.stub(:new) { mock_sprint }
  #     get :new
  #     assigns(:sprint).should be(mock_sprint)
  #   end
  # end
  # 
  # describe "GET edit" do
  #   it "assigns the requested sprint as @sprint" do
  #     Sprint.stub(:find).with("37") { mock_sprint }
  #     get :edit, :id => "37"
  #     assigns(:sprint).should be(mock_sprint)
  #   end
  # end
  # 
  # describe "POST create" do
  #   describe "with valid params" do
  #     it "assigns a newly created sprint as @sprint" do
  #       Sprint.stub(:new).with({'these' => 'params'}) { mock_sprint(:save => true) }
  #       post :create, :sprint => {'these' => 'params'}
  #       assigns(:sprint).should be(mock_sprint)
  #     end
  # 
  #     it "redirects to the created sprint" do
  #       Sprint.stub(:new) { mock_sprint(:save => true) }
  #       post :create, :sprint => {}
  #       response.should redirect_to(sprint_url(mock_sprint))
  #     end
  #   end
  # 
  #   describe "with invalid params" do
  #     it "assigns a newly created but unsaved sprint as @sprint" do
  #       Sprint.stub(:new).with({'these' => 'params'}) { mock_sprint(:save => false) }
  #       post :create, :sprint => {'these' => 'params'}
  #       assigns(:sprint).should be(mock_sprint)
  #     end
  # 
  #     it "re-renders the 'new' template" do
  #       Sprint.stub(:new) { mock_sprint(:save => false) }
  #       post :create, :sprint => {}
  #       response.should render_template("new")
  #     end
  #   end
  # end
  # 
  # describe "PUT update" do
  #   describe "with valid params" do
  #     it "updates the requested sprint" do
  #       Sprint.stub(:find).with("37") { mock_sprint }
  #       mock_sprint.should_receive(:update_attributes).with({'these' => 'params'})
  #       put :update, :id => "37", :sprint => {'these' => 'params'}
  #     end
  # 
  #     it "assigns the requested sprint as @sprint" do
  #       Sprint.stub(:find) { mock_sprint(:update_attributes => true) }
  #       put :update, :id => "1"
  #       assigns(:sprint).should be(mock_sprint)
  #     end
  # 
  #     it "redirects to the sprint" do
  #       Sprint.stub(:find) { mock_sprint(:update_attributes => true) }
  #       put :update, :id => "1"
  #       response.should redirect_to(sprint_url(mock_sprint))
  #     end
  #   end
  # 
  #   describe "with invalid params" do
  #     it "assigns the sprint as @sprint" do
  #       Sprint.stub(:find) { mock_sprint(:update_attributes => false) }
  #       put :update, :id => "1"
  #       assigns(:sprint).should be(mock_sprint)
  #     end
  # 
  #     it "re-renders the 'edit' template" do
  #       Sprint.stub(:find) { mock_sprint(:update_attributes => false) }
  #       put :update, :id => "1"
  #       response.should render_template("edit")
  #     end
  #   end
  # end
  # 
  # describe "DELETE destroy" do
  #   it "destroys the requested sprint" do
  #     Sprint.stub(:find).with("37") { mock_sprint }
  #     mock_sprint.should_receive(:destroy)
  #     delete :destroy, :id => "37"
  #   end
  # 
  #   it "redirects to the sprints list" do
  #     Sprint.stub(:find) { mock_sprint }
  #     delete :destroy, :id => "1"
  #     response.should redirect_to(sprints_url)
  #   end
  # end

end
